[package]
name = "racetrack"
version = "0.2.0"
authors = ["Morten Lohne <lohnemorten@gmail.com>"]
edition = "2018"

[[bin]]
name = "racetrack"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
board-game-traits = "0.1"
pgn-traits = "0.1.0"
taik = { git = "https://github.com/MortenLohne/taik", features = ["pgn-writer"] }
rayon = "1.3"
clap = "2.33"
log = "0.4"